Improve test/test_consumer_integration.py in GitHub runner
test/test_consumer_integration.py::test_kafka_consumer__blocking failed
in
https://github.com/wbarnha/kafka-python-ng/actions/runs/10361086008/job/28680735389?pr=186
because it took 592ms to finish. Output from the GitHub runner attached

This commit increase TIMEOUT_MS so it is less likely to fail on GitHub
runner.

          # Ask for 5 messages, 10 in queue. Get 5 back, no blocking
          messages = []
          with Timer() as t:
              for i in range(5):
                  msg = next(consumer)
                  messages.append(msg)
          assert_message_count(messages, 5)
  >       assert t.interval < (TIMEOUT_MS / 1000.0)
  E       assert 0.5929090976715088 < (500 / 1000.0)
  E        +  where 0.5929090976715088 = <test.testutil.Timer object at 0x7f6c4b50e960>.interval